# Generated by Django 5.0.6 on 2024-07-16 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isdelivery',
            field=models.BooleanField(default=False, verbose_name='Is a delivery agent'),
        ),
        migrations.AddField(
            model_name='user',
            name='surname',
            field=models.CharField(default=1, max_length=256, verbose_name='Surname'),
            preserve_default=False,
        ),
    ]
