# Generated by Django 5.0.6 on 2024-07-16 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_user_isdelivery_user_surname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('BUYER', 'BUYER'), ('SELLER', 'SELLER'), ('SUPPORT', 'SUPPORT')], default='BUYER', max_length=100, verbose_name='account type'),
        ),
    ]
