# Generated by Django 5.0.6 on 2024-07-16 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0004_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='identity.institution'),
        ),
    ]
