# Generated by Django 5.0.6 on 2024-07-16 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0006_rename_institution_user_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='Safe Url'),
        ),
    ]
