# Generated by Django 5.0.6 on 2024-07-16 11:28

import identity.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0007_institution_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='image',
            field=models.FileField(default=1, upload_to=identity.models.get_file_path, verbose_name='Image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.FileField(default='User/user.png', upload_to=identity.models.get_file_path, verbose_name='Image'),
        ),
    ]
