# Generated by Django 5.0.6 on 2024-07-16 13:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0008_institution_image_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='created_on',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Created on'),
        ),
    ]
