# Generated by Django 5.0.6 on 2024-07-20 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0010_user_tel_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tel_number',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Tel number'),
        ),
    ]
