# Generated by Django 5.0.6 on 2024-07-29 22:06

import identity.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0011_alter_user_tel_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.FileField(default='user/user.png', upload_to=identity.models.get_file_path, verbose_name='Image'),
        ),
    ]
