# Generated by Django 5.0.6 on 2024-07-16 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0007_institution_slug'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessInstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.business')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='identity.institution')),
            ],
        ),
    ]
