# Generated by Django 5.0.6 on 2024-07-16 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_businesscategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='Safe Url'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('stock', models.IntegerField(default=0, verbose_name='stock')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Safe Url')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.business')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category')),
            ],
        ),
    ]
