# Generated by Django 5.0.6 on 2024-07-16 11:28

import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_business_slug_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='image',
            field=models.FileField(default=1, upload_to=shop.models.get_file_path, verbose_name='Image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.FileField(default=1, upload_to=shop.models.get_file_path, verbose_name='Image'),
            preserve_default=False,
        ),
    ]
