# Generated by Django 5.0.6 on 2024-07-16 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_order_product_count_order_total_amount_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproduct',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='quantity'),
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='total amount'),
            preserve_default=False,
        ),
    ]
