# Generated by Django 5.0.6 on 2024-07-19 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_business_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='total amount'),
            preserve_default=False,
        ),
    ]
