# Generated by Django 5.0.6 on 2024-07-29 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_order_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('ACCEPTED', 'ACCEPTED'), ('COMPLETED', 'COMPLETED'), ('DECLINED', 'DECLINED')], default='PENDING', max_length=100, verbose_name='status'),
        ),
    ]
